### ISSUE TITLE
How would this work in practice?

### ISSUE THREAD

**Issue by mattip** [Julian/named-branch-action#1]
How would one go about using this in practice? Is there a way to see this in action?

**Comment by mattip** [comment]
Hmm, this should be `@testing` https://github.com/Julian/named-branch-action/blob/b8b9374861fa21f7b746b45462c2f867ffa7a0d0/workflow.yml#L9

**Comment by mattip** [comment]
Oy, github actions must have changed.
```
Current runner version: '2.279.0'
Operating System
Virtual Environment
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2'
Download action repository 'Julian/named-branch-action@testing'
Error: Julian/named-branch-action/testing/action.yml (Line: 16, Col: 7):
Error: Julian/named-branch-action/testing/action.yml (Line: 17, Col: 7):
Error: Julian/named-branch-action/testing/action.yml (Line: 16, Col: 7): Unrecognized named-value: 'github'. Located at position 18 within expression: join('https://', github.actor, ':', inputs.repo-token, '@github.com/', github.repository)
Error: Julian/named-branch-action/testing/action.yml (Line: 17, Col: 7): Unrecognized named-value: 'github'. Located at position 1 within expression: github.ref
Error: Fail to load Julian/named-branch-action/testing/action.yml

```

**Comment by Julian** [comment]
I think all that gets templated now i.e. `${{ github.actor }}`

**Comment by mattip** [comment]
I tried this out on a "clean" repo, and got `fatal: couldn't find remote ref refs/notes/branch`
https://github.com/mattip/named-branch-test/runs/3245407502?check_suite_focus=true#step:3:4

Do I need to do something when initializing my repo?

**Comment by Julian** [comment]
Ups, no, I needed to ignore pulling the notes for a fresh repo. Try again now I think.

**Comment by mattip** [comment]
Cool it works with `git notes --ref branch show HEAD`, but if I push 2 commits it will not mark `HEAD~1` (as you said on IRC).

Also: maybe document that if you do `git config core.notesRef refs/notes/branch` then notes will show up with `git log --notes`.

**Comment by Julian** [comment]
I'll implement the looping tomorrow or so. And yes good idea!

**Comment by Julian** [comment]
OK I gave that a shot in the commit I just pushed. Let me know how it looks.
